apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKICAgICAgICAiZ2hjci5pbyI6IHsKICAgICAgICAgICAgImF1dGgiOiAiYTNKMmFYUmhiRHBuYUhCZmJXdDRZemxqUlU1WU1USlVRemhxYzBST2R6VnNXRlZ0YUhBNVprUkxNMmRuU2psMSIKICAgICAgICB9Cgl9LAoJImNyZWRzU3RvcmUiOiAib3N4a2V5Y2hhaW4iLAoJImN1cnJlbnRDb250ZXh0IjogIm9yYnN0YWNrIiwKCSJwbHVnaW5zIjogewoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9Cg==
type: kubernetes.io/dockerconfigjson
